name = "auth"
type = "webpack"
account_id = "${{ secrets.CF_ACCOUNT_ID }}"
workers_dev = true
route = ""
zone_id = ""
webpack_config = "webpack.config.js"

[site]
bucket = "./public"
entry-point = "."

[[kv_namespaces]]
binding = "AUTH_STORE"
id = "${{ secrets.CF_KV_NAMESPACE_ID }}"